### ISSUE TITLE
Texture atlas creation failing on OnlyMyRailgun

### ISSUE THREAD

**Issue by delroth** [marcan/blitzloop#4]
```
Traceback (most recent call last):
  File "/home/delroth/work/blitzloop/graphics.py", line 85, in _render
    self.frames.next()
  File "main.py", line 145, in main
    for i in main_render():
  File "main.py", line 113, in main_render
    song_layout = layout.SongLayout(qe.song, variant_key, renderer)
  File "/home/delroth/work/blitzloop/layout.py", line 386, in __init__
    self._merge_lines()
  File "/home/delroth/work/blitzloop/layout.py", line 434, in _merge_lines
    tmp.add(molecule, get_atom_time, tag_info.style, font, ruby_font)
  File "/home/delroth/work/blitzloop/layout.py", line 234, in add
    glyph = font.get_glyph(c)
  File "/home/delroth/work/blitzloop/texture_font.py", line 353, in get_glyph
    raise Exception("Atlas is full")
Exception: Atlas is full
```

**Comment by delroth** [comment]
Actually has nothing with playing multiple songs in a row. Happens when trying to load OnlyMyRailgun on my computer -- not sure why the binpacking would do the wrong thing on my system.

**Comment by marcan** [comment]
Slightly different font rendering? The real problem here, of course, is that there is no support for expanding the atlas if it gets full.

Can you get a dump of the atlas at the point where it errors out?

**Comment by delroth** [comment]
Couldn't reproduce recently, closing. Not sure what caused it to fail at that point.
